### ISSUE TITLE
请教，如果用这个 repo 做实验，该从那个分支开始

### ISSUE THREAD

**Issue by icecraft** [monkey2000/xv6-riscv-fall19#2]
请教，如果用这个 repo 做实验，该从那个分支开始 （我没有找到比这个更新的 repo 了）

**Comment by monkey2000** [comment]
这个 repo 是我自己的 MIT 6.S081 2019 课程实验的解答（有很多错误）。

官方版的空白代码框架：https://github.com/mit-pdos/xv6-riscv-fall19 ，实验指导：https://pdos.csail.mit.edu/6.828/2019/ 。
